### ISSUE TITLE
Restyle app with new brand look & feel

### ISSUE THREAD

**Issue by efstajas** [radicle-dev/drips-app-v2#114]

**Comment by brandonhaslegs** [comment]
To do:
- [ ] Update raindrops in stream view to outline style
- [ ] make all outlines `foreground`
- [ ] make modal border radius 32px (with top right 0px)
- [ ] all inputs, buttons, border, warning boxes,  radius 24px (with top right 0px)
- [ ] adjust buttons and inputs to have more (20px in the design file) left and right padding. due to the pointy border radius, this padding looks better.
- [ ] remove box shadow on modals
