### ISSUE TITLE
Section borders glitchy

### ISSUE THREAD

**Issue by CodeSandwich** [radicle-dev/drips-app-v2#184]
The glitchiness changes when scaling the entire page, some borders get fixed, some start breaking. Examples:

![image](https://user-images.githubusercontent.com/26183680/205303895-dff4e314-79b3-4f98-9a3f-8289a69bbdf7.png)

Here the white bar on the right is this thick when hovering over it, when not hovering, it's just as long, but thinner.

![image](https://user-images.githubusercontent.com/26183680/205304463-c13f6f1f-ab63-4496-a9e9-5e780a8d65b1.png)

**Comment by efstajas** [comment]
Re issue #1 that's a GREAT find haha. The problem is that with these fractional pixels that occur when scaling down the 1px wide border, apparently browsers sometimes render the line exactly between two virtual pixels, but the section component sets its height to precisely the reported height of the content, resulting in the line being cut off. I'll just always add `+1px` to the height of the section, and it should fix it.

Re issue #2, that's super weird 🤨 Cannot reproduce that on my end. Could it be related to your pixel ratio situation maybe?

**Comment by CodeSandwich** [comment]
I don't think that the hovering issue is related to the pixel ratio. There should be nothing to hover over in the first place. Also, we should not let the page design go to drain when the browser has a different scaling or screen scaling than the devs 🙃

**Comment by CodeSandwich** [comment]
I think that the white bar may be a scroll bar handle, which gets bigger when hovering:

![image](https://user-images.githubusercontent.com/26183680/205311561-1a2cea60-d466-4a72-8114-76d2424477a1.png)

**Comment by efstajas** [comment]
> I don't think that the hovering issue is related to the pixel ratio. There should be nothing to hover over in the first place. Also, we should not let the page design go to drain when the browser has a different scaling or screen scaling than the devs 🙃 That's the entire point of web apps, they should render and look good enough anywhere.

100% agree, never meant to say otherwise :) 

> Yes, this is it, disabling overflow-y: scroll; on this element fixes both the thick bar on the side and the lack of the bottom border of the section.

Aha!! Thanks. I didn't catch that because macOS (unfortunately) doesn't render scrollbars unless you're scrolling. Will disable overflow, together with the +1px fix it should fix both problems.

**Comment by efstajas** [comment]
#186 should fix it for good — deploy should be done in max 5 minutes. Feel free to re-open if you see it again!

**Comment by CodeSandwich** [comment]
It's fixed, thanks!
