### ISSUE TITLE
Bug - Inconsistent collectable amount 

### ISSUE THREAD

**Issue by bordumb** [radicle-dev/drips-app-v2#258]
## Overview

See video below.

Issue I encountered was:
1. Have a collectable amount in my home page 
2. Collect all of it in the collect modal
3. Close the collect modal and the home page still has the old collectable amount 

I'd expect at step 3 that the amount will have gone to `0.0`

Note that the modal is correctly displaying `0.0`

So it seems the home page has some caching issue 

https://user-images.githubusercontent.com/3743841/209238183-a0ea7967-7e29-4765-a059-6fccb8f57ce7.mov

**Comment by efstajas** [comment]
This is currently unfortunately "expected behavior" — the collectable amount shown in real-time is just the total ever earned from any incoming streams. It's described as such in the little ( i ) tooltip on the homepage.

Of course, we want to change this, but it's not trivial. The issue do that is #62. There are only a few small blockers on the SDK side remaining before we can start working on that. Once resolved, the collectable amount shown should always equal exactly how much the user could currently collect if they were to squeeze all their incoming streams, before splitting, and thus also go down back to zero after collecting.

Let's keep this issue open & mark both as resolved when that's done 👍
