### ISSUE TITLE
On load page transition

### ISSUE THREAD

**Issue by brandonhaslegs** [radicle-dev/drips-app-v2#313]
- [ ] The page fades from black, when it should fade from white.
- [ ] The nav animates to the top of the viewport, then just jumps down to its position.

**Comment by efstajas** [comment]
@brandonhaslegs 

> The page fades from black, when it should fade from white.

What you're referring to is called a [FART](https://css-tricks.com/flash-of-inaccurate-color-theme-fart/).

The server unfortunately has no way to know which theme the user has selected when rendering the page. This means we had to make a decision whether to render the page in dark mode or light mode server-side. Because apparently the majority of people are using dark mode (according to some quick superficial research), I went with dark mode as the default. If you're in light mode, what's happening is that the server sends you the pre-rendered page in dark mode, then sends the javascript, and once that's downloaded the javascript executes and selects the "correct" theme given the user's settings.

There's [some standards developing](https://web.dev/user-preference-media-features-headers/) that would give the server a way to know the selected theme while rendering the page. Until then, we're stuck with having to make a guess.

**Comment by brandonhaslegs** [comment]
I more think the page loading in animation is not worth a FART…

**Comment by efstajas** [comment]
Without the animation it's even worse. The FART is still there, and doesn't fade. I added the animation as a FART hiding tactic.

**Comment by brandonhaslegs** [comment]
Just seems like you're more intentionally FARTing when you fade it.

**Comment by brandonhaslegs** [comment]
Anyway what about the second point? That it jumps?

**Comment by efstajas** [comment]
> Just seems like you're more intentionally FARTing when you fade it.

Here's an old deployment before the transition: https://drips-app-v2-1qma8ecr7-radicle.vercel.app/ Wdyt?

> Anyway what about the second point? That it jumps?

Yeah, I noticed that but somewhat didn't care because it only happens if you reload the page while scrolled down. Should definitely fix at some point, so let's keep this issue to track that.

**Comment by efstajas** [comment]
[0eacd5f](https://github.com/radicle-dev/drips-app-v2/commit/0eacd5f397b4cd47b51ced90e07fd186b775472f)

⬆️ This will fix the problem with the glitchy header bar, but won't fix the fart.
